---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task-container
          image: tlprdocker/task:latest          
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
          resources:
            limits:
              cpu: 1
              memory: 700Mi
            requests:
              cpu: 1
              memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
